apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard-stage
spec:
  secretName: certificate-stg-wildcard
  commonName: '*.coontie.com'
  dnsNames:
  - coontie.com
  - '*.coontie.com'
  issuerRef:
    name: letsencrypt-wildcard-issuer
    kind: Issuer